FROM node:20-slim

# Installe ffmpeg (nécessaire pour assembler les vidéos)
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .

ENV PORT=3000
EXPOSE 3000

CMD ["node", "server.js"]
